*** Variables ***
# Extracted dictionary mapping error numeric IDs to clear string labels
&{ERROR_CODES}    1=INVALID_PARAMS
...               2=BUFFER_FULL
...               3=CANNOT_ABORT
...               4=HARDWARE_ERROR
...               5=DEVICE_DISABLED
...               6=DEVICE_DEACTIVATED
...               7=ALREADY_QUEUED
...               8=LOCATION_UNAVAILABLE
...               9=ALREADY_IN_SESSION
...               10=RESOURCE_ERROR
...               11=NOT_FOUND
...               12=BAD_STATE
...               13=ALREADY_EXISTS
...               14=PERMISSION_ERROR
...               15=TX_LIFTIME_EXPIRED
...               16=TX_NO_LOW_PRIORITY_TO_SORT
...               17=TX_LIFETIME_NOT_SET
...               18=TX_TEMP_OUTOFRANGE
...               19=INVALID_DATETIME
...               20=TASK_HANDLE_NULL
...               21=TX_RESP_ERROR
...               22=BUSY
...               23=TX_QUEUE_EMPTY
...               24=BUFFER_EMPTY
...               25=SOS_MODE_ENABLED
...               26=NO_DEVICE_PLAN
